### PR TITLE
Use browser-sync instead of gulp-live-server

### PR DESCRIPTION
**Pull request by sprql**
It looks like `gulp-live-server` is slightly outdated, 
also it didn't work for me

### CODE REVIEW

**Comment by pilafmon** [comment]
I don't encounter the problem locally, but **Travis CI** is failing with:
```
The command "yarn --frozen-lockfile" failed and exited with 1 during .
```

**Comment by pilafmon** [comment]
It looks like we both investigating this problem at the same time.

I replicated the failure with: ceb8567fe64

...then fixed it by simply removing the old **yaml.lock** file: 642441b

**Comment by sprql** [comment]
Yeah, now everything seems to be fine

**Comment by pilafmon** [comment]
Release v1.9.4

**Pull request merged**
